version: '3'

services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hr
      - POSTGRES_USER=hr
      - POSTGRES_PASSWORD=test
